export const StackNav = {
  Auth: 'Auth',
  Splash: 'Splash',
  WelcomeScreen: 'WelcomeScreen',
  HomeTab:'HomeTab',
  AudioFiles: 'AudioFiles',
  ListScreen:'ListScreen',
  DetailScreen: 'DetailScreen',
  Music: 'Music',
  About: 'engalaipatria',
  WahdatulWujud:'Vahdhathulujjuth/:Vahdhathulujjuth',
  GnanaAgamiyas:'GnanaAgamiyas',
  Books:'Books',
  Programs:'Programs',
  Education:'Education/:Education',
  Manitha:'manitha/:manitha',
  Collections:'Collections/:Collections',
  EmsDetailScreen:'EmsDetailScreen',
  Quiz:'Quiz',
  PhotoGallery:'நிகழ்ச்சிகள்/pugaipadangal/:category',
  VideoGallery: 'நிகழ்ச்சிகள்/kaanoli/:category',
  AudioGallery: 'AudioGallery',
  Login: 'Login',
  SignUp:'SignUp',
  ForgotPass:'ForgotPass',
  LogOutPage:'LogOutPage',
  CreateNewPassword:'CreateNewPassword',
  PlayAudio:'PlayAudio',
  ProductList:'ProductList',
  ProductViewCart:'ProductViewCart',
  PaymentSelect:'PaymentSelect',
  ProductAddCart:'ProductAddCart',
  Magazine:'Magazine',
  Event:'Event',
  Payment:'Payment',
  Articles:'Articles',
  Profile:'Profile',
  PlayAudioGallery:'PlayAudioGallery',
};
